# Generated by Django 3.2.8 on 2022-01-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0002_auto_20220120_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
