# Generated by Django 3.2.8 on 2021-11-25 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0003_auto_20211124_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='requests',
        ),
    ]
