# Generated by Django 3.2.8 on 2022-04-15 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUser', '0004_alter_profile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expert',
            name='description',
        ),
    ]
