# Generated by Django 3.2.8 on 2021-10-31 09:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='attachment/')),
                ('created_at', models.DateField(blank=True, default=datetime.datetime(2021, 10, 31, 14, 54, 10, 894649), null=True)),
                ('updated_at', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='media/')),
                ('created_at', models.DateField(blank=True, default=datetime.datetime(2021, 10, 31, 14, 54, 10, 894649), null=True)),
                ('updated_at', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
