# Generated by Django 3.2.8 on 2021-11-24 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaField', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='created_at',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='created_at',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
