# Generated by Django 3.2.8 on 2021-10-31 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mediaField', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('completion_Date', models.DateField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('attachment', models.ManyToManyField(to='mediaField.File')),
                ('gallery', models.ManyToManyField(to='mediaField.MediaFile')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Task.topic')),
            ],
        ),
    ]
