# Generated by Django 3.2.8 on 2021-11-25 04:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Task', '0003_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='doer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_doer', to=settings.AUTH_USER_MODEL),
        ),
    ]
