# Generated by Django 3.2.8 on 2021-11-26 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Task', '0004_task_doer'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(1, 'unassigned'), (2, 'working'), (3, 'validating'), (4, 'reforming'), (5, 'completed')], default=1),
        ),
    ]
